### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by aviaryan** [singhpratyush/hotstar-playlist-downloader#1]
In description, we have HotStart instead of HotStar

**Comment by singhpratyush** [comment]
Thanks. Was in a hurry while writing. Time and Internet Speed waits for none.

**Comment by aviaryan** [comment]
I get time but how is "Internet speed" going away ?

**Comment by singhpratyush** [comment]
I've less restriction on speed and no restriction on transfer limit on my college Cyberoam account right now. Which may not last for long.

Also since you guys are away, Joi performs well. Trying to make use of it. :P
