### ISSUE TITLE
Add eclint to Tracis CI

### ISSUE THREAD

**Issue by singhpratyush** [singhpratyush/hotstar-playlist-downloader#11]

**Comment by riktimmondal** [comment]
What is eclint ?

**Comment by singhpratyush** [comment]
`eclint` tests the code against `.editorconfig` file present in the repo. If added to travis CI, it will make the build to fail soon as there is inconsistency with in the code.

[eclint](https://github.com/jedmao/eclint)
[editorconfig](http://editorconfig.org/)

**Comment by singhpratyush** [comment]
Here is an example - https://github.com/iiitv/algos/blob/master/.travis.yml#L21

**Comment by singhpratyush** [comment]
We won't need eclint as we already have pep8 bear install with coala.

Sorry about this issue.
