### ISSUE TITLE
Not able send PR

### ISSUE THREAD

**Issue by riktimmondal** [singhpratyush/hotstar-playlist-downloader#13]
![screenshot from 2017-10-11 15-08-09](https://user-images.githubusercontent.com/24415468/31433192-3485ac2a-ae96-11e7-9e41-a190a0604abc.png)

**Comment by singhpratyush** [comment]
You need to fork the repository and send a PR using your version of the repo.

[This](https://www.thinkful.com/learn/github-pull-request-tutorial/#Time-to-Submit-Your-First-PR) may be helpful.

Closing the issue since it is not related to this repository.
