### ISSUE TITLE
non existing SPS

### ISSUE THREAD

**Issue by dev-1995** [singhpratyush/hotstar-playlist-downloader#17]
[NULL @ 000001dfecb0b1a0] non-existing SPS 0 referenced in buffering period
[NULL @ 000001dfecb0b1a0] SPS unavailable in decode_picture_timing
[h264 @ 000001dfecb1e700] non-existing SPS 0 referenced in buffering period
[h264 @ 000001dfecb1e700] SPS unavailable in decode_picture_timing

i don't know how to fix this

**Comment by singhpratyush** [comment]
Though I think that the problem is not related to this repository, it would be easier if you could give more details like what you entered to run this and a few details from downloader.

**Comment by dev-1995** [comment]
python hotstar-playlist-downloader.py http://www.hotstar.com/tv/devon-ke-dev-mahadev/12/episodes/12/9992 
ffmpeg version N-88042-g72c3d9ae45 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
  libavutil      56.  0.100 / 56.  0.100
  libavcodec     58.  0.100 / 58.  0.100
  libavformat    58.  0.100 / 58.  0.100
  libavdevice    58.  0.100 / 58.  0.100
  libavfilter     7.  0.100 /  7.  0.100
  libswscale      5.  0.100 /  5.  0.100
  libswresample   3.  0.100 /  3.  0.100
  libpostproc    55.  0.100 / 55.  0.100
[hls,applehttp @ 000001dfeca92140] Opening 'https://staragvod-vh.akamaihd.net/i/videos/lifeok/dekedema/820/1000044237_,16,54,106,180,400,800,1300,2000,3000,4500,_STAR.mp4.csmil/crypt.key?null=0&id=AgAOi%2fJtfHz8B1qn7Vk0Zp1hrP8o0BzvCqFhpCVk0VplwjwZkgTb+LzoWfu+XExJZFCoC6wEZ4rBLQ%3d%3d' for reading
[hls,applehttp @ 000001dfeca92140] Opening 'crypto+https://staragvod-vh.akamaihd.net/i/videos/lifeok/dekedema/820/1000044237_,16,54,106,180,400,800,1300,2000,3000,4500,_STAR.mp4.csmil/segment1_9_av.ts?null=0&id=AgAOi%2fJtfHz8B1qn7Vk0Zp1hrP8o0BzvCqFhpCVk0VplwjwZkgTb+LzoWfu+XExJZFCoC6wEZ4rBLQ%3d%3d' for reading
[NULL @ 000001dfecb0b1a0] non-existing SPS 0 referenced in buffering period
[NULL @ 000001dfecb0b1a0] SPS unavailable in decode_picture_timing
[h264 @ 000001dfecb1e700] non-existing SPS 0 referenced in buffering period
[h264 @ 000001dfecb1e700] SPS unavailable in decode_picture_timing
Input #0, hls,applehttp, from 'https://staragvod-vh.akamaihd.net/i/videos/lifeok/dekedema/820/1000044237_,16,54,106,180,400,800,1300,2000,3000,4500,_STAR.mp4.csmil/index_9_av.m3u8?null=0&id=AgAOi%2fJtfHz8B1qn7Vk0Zp1hrP8o0BzvCqFhpCVk0VplwjwZkgTb+LzoWfu+XExJZFCoC6wEZ4rBLQ%3d%3d':
  Duration: 00:43:54.28, start: 0.100667, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Mahdev enlightens about unity-1000044237.mp4.part':
  Metadata:
    encoder         : Lavf58.0.100
    Stream #0:0: Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  133 fps=0.0 q=-1.0 size=    2816kB time=00:00:05.29 bitrate=4360.3kbits/s speed=10.6x

**Comment by singhpratyush** [comment]
This is not an issue. You can download the episode(s) anyway.

You can get more information about `non-existing SPS XX referenced in buffering period - error while encoding UDP stream` [here](https://trac.ffmpeg.org/ticket/1326).
