### ISSUE TITLE
season episode download incorrect

### ISSUE THREAD

**Issue by pra7792dip** [singhpratyush/hotstar-playlist-downloader#9]
Hi,

First of all thanks for providing valuable information. I was able to download all episodes from season1-3. But from season4, it download false url videos.

I mean, when I try to download season4, it downloads some other videos.

> http://www.hotstar.com/tv/devon-ke-dev-mahadev/12/seasons/season-4 

the video start from:

> http://www.hotstar.com/1000000349 to http://www.hotstar.com/1000000382

but instead of that it downloads :

> http://www.hotstar.com/1000000039 then http://www.hotstar.com/1000000909-921

**Comment by pra7792dip** [comment]
Hi,

Still it fetches different link.

The link should be start from:

> http://www.hotstar.com/1000022452

to 

> http://www.hotstar.com/1000022462

 Please check output:

```

> ./hotstar-playlist-downloader.py http://www.hotstar.com/tv/devon-ke-dev-mahadev/12/seasons/season-31


http://account.hotstar.com/AVS/besc?action=GetArrayContentList&appVersion=5.0.40&categoryId=28&channel=PCTV
Downloading http://www.hotstar.com/1000000315
[HotStar] 1000000315: Downloading JSON metadata
[HotStar] 1000000315: Downloading JIO JSON metadata
[HotStar] 1000000315: Downloading m3u8 information

```

**Comment by singhpratyush** [comment]
I assumed something incorrectly. Please try now.
